'use client'
import { ToolNav, ToolFooter } from '../components/ToolChrome'

export default function Terms() {
  return (
    <div style={{ minHeight: '100vh', background: '#fff', color: '#161616', fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif' }}>
      <ToolNav />
      <main style={{ maxWidth: '760px', margin: '0 auto', padding: 'clamp(2rem,5vw,4rem) clamp(1rem,4vw,1.5rem)' }}>
        <div style={{ marginBottom: '3rem' }}>
          <p style={{ fontSize: '0.8rem', fontWeight: 600, color: '#8a8a8a', textTransform: 'uppercase', letterSpacing: '0.12em', marginBottom: '0.9rem' }}>Legal</p>
          <h1 style={{ fontSize: 'clamp(1.7rem,4.5vw,2.6rem)', fontWeight: 700, margin: '0 0 0.5rem', letterSpacing: '-0.02em' }}>Terms of Service</h1>
          <p style={{ color: '#8a8a8a', margin: 0 }}>Last updated: March 2025</p>
        </div>

        {[
          { title: 'Acceptance of terms', content: 'By accessing or using IsItAI, you agree to these Terms of Service. If you do not agree, please do not use the service. We may update these terms at any time — continued use constitutes acceptance of any changes.' },
          { title: 'What IsItAI is', content: 'IsItAI is an AI image detection tool that analyzes uploaded images and returns a probabilistic assessment of whether the image was generated by artificial intelligence. Results are statistical estimates, not legal determinations or guaranteed facts. The service is provided for informational purposes only.' },
          { title: 'Accuracy and limitations', content: 'IsItAI uses machine learning models and forensic heuristics to make predictions. These predictions are probabilistic and not infallible. We make no guarantee of accuracy. You should not rely solely on IsItAI results to make important decisions — always apply your own judgment and consult additional sources when the stakes are high.' },
          { title: 'Permitted use', content: 'You may use IsItAI for personal, educational, journalistic, or professional research purposes. You may not use IsItAI to harass individuals, make defamatory claims about specific people, circumvent legal processes, or build competing services by scraping our outputs. You may not attempt to reverse-engineer, overload, or exploit our infrastructure.' },
          { title: 'Images you submit', content: 'By uploading an image, you confirm that you have the right to submit it for analysis. You retain all ownership of your content. You grant IsItAI only the minimal, temporary right to process the image for detection. We do not claim any ownership over your images.' },
          { title: 'Prohibited content', content: 'Do not upload images that are illegal, involve child sexual abuse material (CSAM), constitute targeted harassment of real individuals, or violate any applicable law. We reserve the right to block access to users who submit prohibited content and to report illegal content to the appropriate authorities.' },
          { title: 'No warranties', content: 'IsItAI is provided "as is" without warranties of any kind, express or implied. We do not warrant that the service will be uninterrupted, error-free, or available at all times. We reserve the right to modify, suspend, or discontinue the service at any time without notice.' },
          { title: 'Limitation of liability', content: 'To the fullest extent permitted by applicable law, IsItAI and its creators are not liable for any indirect, incidental, special, or consequential damages arising from your use of the service. This includes damages from incorrect detections, reliance on our results, or service interruptions.' },
          { title: 'Governing law', content: 'These terms are governed by applicable law. Disputes arising from use of the service should first be directed to us at ' + (process.env.CONTACT_EMAIL || 'contact@isitai.app') + ' for informal resolution before pursuing formal legal action.' },
          { title: 'Contact', content: 'Questions about these terms? Email us at ' + (process.env.CONTACT_EMAIL || 'contact@isitai.app') + '. We are a small team and will respond to legitimate inquiries promptly.' },
        ].map((section, i) => (
          <div key={i} style={{ marginBottom: '2.5rem', paddingBottom: '2.5rem', borderBottom: i < 9 ? '1px solid rgba(0,0,0,0.06)' : 'none' }}>
            <h2 style={{ fontSize: '1.1rem', fontWeight: 700, margin: '0 0 0.75rem' }}>{section.title}</h2>
            <p style={{ color: '#5c5c5c', lineHeight: 1.8, margin: 0, fontSize: '0.95rem' }}>{section.content}</p>
          </div>
        ))}
      </main>
      <ToolFooter />
    </div>
  )
}