// ─── Plain-language explanations for every detection signal ─────────────────
// Maps a signal label (or prefix) to a human explanation shown in the UI so
// users understand WHY something was flagged, not just THAT it was flagged.

const EXACT = {
  'No EXIF data':
    'The file carries no camera metadata at all. Real in-camera photos almost always include EXIF; AI generators and most social-media re-encodes strip it. (Note: messaging apps can also strip EXIF, so this alone is not proof.)',
  'Real photos always have metadata':
    'Cameras and phones embed make, model, exposure and timing data into JPEGs. Its complete absence is a moderate AI indicator.',
  'No software field':
    'Genuine camera files usually name the processing software. An empty Software tag slightly raises suspicion.',
  'No camera data':
    'No Make/Model tags were found. Phones and cameras always write these; AI pipelines generally do not.',
  'GPS recorded':
    'Location metadata present — typical of phone/camera photos with geotagging enabled.',
  'No GPS':
    'Absence of GPS is common even for real photos (geotagging is often off), so this is only a weak signal.',
  'No lens data':
    'Lens/focal-length tags are missing. Many real compact/phone photos omit them too — weak signal.',
  'No timestamp':
    'No capture datetime found. Cameras stamp DateTimeOriginal; AI outputs rarely do.',
  'Metadata parse failed':
    'The metadata block could not be read (corrupt or unusual format). Treated as neutral-to-slightly-suspicious.',
  'GAN frequency artifacts':
    'The pixel-frequency spectrum shows the periodic fingerprints left by GAN/diffusion upsampling layers.',
  'Elevated high-frequency energy':
    'Unusual high-frequency energy distribution compared with natural photographs.',
  'Natural frequency distribution':
    'The frequency spectrum decays like a typical camera photo (1/f noise).',
  'Unnaturally smooth texture':
    'Local texture variance is abnormally low — diffusion models tend to over-smooth skin, fabric and foliage.',
  'Natural texture variance':
    'Sensor-noise-like variance present across small image blocks, consistent with a real camera.',
  'Face/skin detected':
    'Skin-toned regions were found, enabling an extra facial-symmetry check.',
  'No face detected':
    'No face-like skin regions — symmetry heuristics skipped.',
  'Unnatural symmetry':
    'Near-perfect left/right luminance symmetry. Real faces are asymmetric; GAN faces are eerily symmetric.',
  'High symmetry':
    'Stronger-than-typical facial symmetry — mild AI indicator.',
  'Natural asymmetry':
    'Facial asymmetry within the normal human range — supports authenticity.',
  'Irregular dimensions — real camera pattern':
    'Sensor resolutions produce specific odd dimension sets; AI generators output round, grid-aligned sizes.',
  'high-res camera photo':
    'Very large megapixel counts currently exceed most consumer text-to-image generators.',
  'Multiples of 128 — common AI output size':
    'Diffusion models emit sizes divisible by 128 (latent-space alignment).',
  'Multiples of 64 — possible AI output':
    'Sizes divisible by 64 match common generator latent grids.',
  'C2PA content credentials present':
    'The file embeds C2PA provenance credentials — an industry standard that LABELS whether content was AI-generated or captured by a device.',
  'SynthID watermark detected':
    "Google DeepMind's SynthID invisible watermark pattern was identified — this image was generated by Gemini/Imagen.",
  'GLIGEN watermark detected':
    'The GLIGEN generator watermark was decoded — this image came from a Microsoft research generator.',
  'IPTC DigitalSource set to "artificial intelligent"':
    'Adobe Firefly and friends tag images as AI via the IPTC DigitalSource code per C2PA guidance.',
  'XMP DocumentID/GPT Image tag':
    "OpenAI's GPT-4o image output writes a distinctive XMP DocumentID. Presence suggests an OpenAI generator (could also be copied metadata).",
  'Camera Raw settings block':
    'A full Camera Raw edit history block exists — strong evidence of a genuine RAW photograph edited in Lightroom/Camera Raw.',
  'TIFF thumbnail stripped':
    'JPEGs written by cameras embed a full EXIF structure including a thumbnail. Flattened/re-written EXIF without thumbnails is typical of generator output.',
  'Unknown':
    'This signal has no detailed description yet.',
}

// Prefix rules for dynamic labels like "Exact match: SDXL / DALL-E square (1024×1024)"
const PREFIX = [
  [/^Exact match:/, 'The pixel dimensions exactly match a known default output size of a popular AI generator.'],
  [/^AI tool:/, 'The embedded Software/CreatorTool metadata literally names an AI generator — near-definitive evidence.'],
  [/^Software:/, 'A non-AI application produced or last-saved this file (photo editors legitimately rewrite metadata).'],
  [/^Shot /, 'A capture timestamp exists and parses as a plausible date — consistent with a real photo.'],
  [/^Created /, 'An origin timestamp exists — mildly supportive of authenticity.'],
  [/lens$/, 'Lens model present — only real optics report lens names.'],
  [/mm lens/, 'Focal length present — a classic camera EXIF field.'],
  [/^GPS coordinates/, 'Geolocation tags present — typical of phone cameras.'],
  [/^\d+(\.\d+)?° · /, 'Device orientation tag present — written by physical cameras.'],
  [/^Exposure /, 'Exposure triangle values present — hallmark of real capture metadata.'],
  [/^ISO \d+/, 'ISO sensitivity tag present — hallmark of real capture metadata.'],
  [/^Aspect ratio/, 'The aspect ratio matches a known generator preset (e.g. Midjourney 4:3 → 1344×768).'],
  [/^Square canvas/, 'Perfectly square canvases are the most common AI-generator default.'],
  [/^Digit-round bias/, 'Pixel values cluster suspiciously on rounded numbers — a known artifact of some upscalers/generators.'],
  [/^Quantization table/, 'JPEG tables differ from standard camera encoders — indicates third-party re-encoding (weak signal).'],
  [/^Color profile/, 'ICC color profile present — most AI generators do not embed profiles.'],
  [/^Progressive JPEG/, 'Progressive encoding is chosen by web tools more often than cameras — mildly reduces trust.'],
  [/^Standard baseline/, 'Baseline JPEG layout typical of camera firmware.'],
  [/^Chroma subsampling/, 'Subsampling pattern checked against typical camera vs. generator behaviour.'],
  [/^Noise residual/, 'Residual after median filtering estimates sensor noise. Low relative noise suggests synthetic smoothness; very high suggests post-sharpening.'],
  [/^Block-boundary energy/, 'Measures ringing at 8×8 JPEG block borders. Diffusion images show unusually flat block statistics.'],
  [/^Grid autocorrelation peak/, 'Periodic patterns at 8/16 px intervals betray GAN transposed-convolution upsampling.'],
  [/^Saturation extremes/, 'Hyper-saturated colors outside typical photographic gamuts hint at generative styling.'],
  [/^White balance lockstep/, 'Suspiciously uniform channel means suggest algorithmic rather than optical capture.'],
  [/^Highlight clipping/, 'Digital highlight rolloff differs between sensors and generators.'],
  [/^Histogram combing/, 'Banded histograms appear when images are synthetically quantized or heavily posterized.'],
  [/^Edge density/, 'Extremely uniform edge density is characteristic of generated textures.'],
  [/^Frequency decay exponent/, 'Natural photos follow a predictable power-law spectral decay; deviations flag synthesis.'],
  [/^Local contrast CV/, 'Coefficient of variation of local contrast — sensors produce heavier tails than generators.'],
  [/^Channel correlation/, 'R/G/B channels of real scenes correlate strongly; generators sometimes decorrelate them.'],
  [/^EXIF IFD parsed/, 'Structured EXIF directory successfully parsed from the file.'],
  [/^APP1 segment/, 'EXIF APP1 marker segment located in the JPEG stream.'],
  [/^MakerNote present/, 'Vendor-specific MakerNote found — only physical camera firmware writes these.'],
  [/^Orientation tag/, 'Orientation tag present — written by camera firmware auto-rotate logic.'],
  [/^Color space/, 'Colorspace tag present — typical of camera EXIF writers.'],
  [/^Unique Camera ID/, 'Some phones embed a per-device unique identifier — impossible for generators to forge.'],
]

export function explainSignal(label) {
  if (!label) return EXACT['Unknown']
  if (EXACT[label]) return EXACT[label]
  for (const [re, txt] of PREFIX) {
    if (re.test(label)) return txt
  }
  return EXACT['Unknown']
}

export function describeModel(name) {
  const n = (name || '').toLowerCase()
  if (n.includes('umm-maybe')) return 'Community-trained classifier over GAN and early diffusion outputs (ViT backbone).'
  if (n.includes('haywoodsloan')) return 'Fine-tuned detector with the highest sensitivity on modern diffusion generators (SDXL, Midjourney v6+, Flux).'
  if (n.includes('umitkaya')) return 'Hugging Face “best AI image detector” ensemble checkpoint — broad coverage across many generator families.'
  if (n.includes('shunk0211')) return 'Multimodal model — reads BOTH the image and any embedded prompt/metadata text.'
  return 'Hugging Face vision classifier used as a second opinion.'
}
