// ─── isitext pipeline orchestrator ───────────────────────────────────────────
// Mirrors lib/analyze.js for the image detector: fuses statistical stylometry,
// structure checks, AI-trace fingerprints, an optional worker model and
// sentence-level localization into ONE response shape the shared UI consumes:
//   { kind, score, band, verdict, confidence, degraded, layers{...}, saliency }
// Every layer exposes `signals: [{label, suspicious, why}]` so the frontend can
// render per-layer evidence cards with explanations, exactly like images.

import { analyzeTextFeatures, analyzeTextLocalization, classifyTextWithWorker } from './textDetect.js'
import { explainSignal } from './signals.js'

const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v))

// ─── Layer 2: text structure & formatting tells ──────────────────────────────
export function analyzeTextStructure(text) {
  const clean = String(text || '')
  const lines = clean.split('\n')
  const signals = []
  let s = 0

  const headings = lines.filter(l => /^#{1,6}\s/.test(l.trim())).length
  const bullets = lines.filter(l => /^\s*[-*•]\s+/.test(l)).length
  const numbered = lines.filter(l => /^\s*\d+[.)]\s+/.test(l)).length
  const nonEmpty = lines.filter(l => l.trim()).length
  const listDensity = nonEmpty ? (bullets + numbered) / nonEmpty : 0
  const totalWords = (clean.match(/[a-z']+/gi) || []).length

  if (headings >= 3) { s += 8; signals.push({ label: `${headings} markdown headings — chat-format scaffolding`, suspicious: true }) }
  if (listDensity > 0.45 && totalWords > 120) { s += 10; signals.push({ label: `${Math.round(listDensity * 100)}% of lines are list items — heavy bullet structuring typical of assistant replies`, suspicious: true }) }
  if (/^\s*(here'?s|certainly!|absolutely!|i hope this helps|let me know)/im.test(clean)) { s += 12; signals.push({ label: 'Assistant-style framing ("Here\'s…", "Certainly!", "I hope this helps")', suspicious: true }) }
  if (/^\s*(as an ai language model|i don'?t have (personal|feelings)|i'?m sorry, but as)/im.test(clean)) { s += 25; signals.push({ label: 'Self-reference as an AI model — direct trace', suspicious: true }) }
  if (/\*\*[^*\n]{2,60}\*\*/.test(clean) && (clean.match(/\*\*/g) || []).length >= 6) { s += 6; signals.push({ label: 'Frequent bolded key-phrases — markdown emphasis habit of chat output', suspicious: true }) }
  if (/\[\d+\]/.test(clean) && /https?:\/\/\S+/.test(clean)) { s += 4; signals.push({ label: 'Bracketed citations with URLs — retrieval-augmented style', suspicious: true }) }
  const trailing = clean.trimEnd().slice(-60).toLowerCase()
  if (/(in conclusion|overall,|to summarize|hope that helps)/.test(trailing)) { s += 6; signals.push({ label: 'Formulaic closing summary', suspicious: true }) }
  if (!signals.length) signals.push({ label: 'No structural chat-format tells detected', suspicious: false })

  return { score: clamp(s, 0, 90), signals, confidence: totalWords > 150 ? 'medium' : 'low' }
}

// ─── Layer 3: known-LLM fingerprint scan (watermarks & traces) ───────────────
export function scanAiTraces(text) {
  const lower = String(text || '').toLowerCase()
  const signals = []
  let maxScore = 0

  // OpenAI's Oyster synthetic-data watermark: balanced rare-word pairs in
  // order to flip a bit. A dense cluster of these low-frequency words inside
  // short spans is a strong hint of watermarked training/synthetic output.
  const RARE = ['accept', 'against', 'answer', 'area', 'army', 'article', 'artist', 'authority', 'baby', 'backend', 'ball', 'bank', 'base', 'bath', 'bear', 'beat', 'bed', 'begin', 'beyond', 'bind', 'bit', 'bite', 'blend', 'block', 'board', 'bold', 'bond', 'book', 'boost', 'boot', 'border', 'born', 'boss', 'bottom', 'bowl', 'brain', 'brand', 'breath', 'brief', 'bring', 'broadcast', 'browser', 'budget', 'building', 'burn', 'button', 'cabin', 'cable', 'calm', 'camera', 'cancel', 'canvas']
  const rareHits = RARE.filter(w => new RegExp(`\\b${w}\\b`).test(lower)).length
  const rarePerK = rareHits / Math.max(lower.split(/\s+/).length / 1000, 0.2)
  if (rarePerK >= 18) { maxScore = Math.max(maxScore, 78); signals.push({ label: `Dense low-frequency word clustering (${rareHits} marker-class hits) consistent with an LLM lexical watermark (e.g. OpenAI Oyster)`, suspicious: true }) }

  // Explicit provenance strings people leave in pasted chat output
  const TRACE_PATTERNS = [
    [/chatgpt|gpt-\d|openai/i, 'ChatGPT/GPT identifier present in the text'],
    [/claude|anthropic/i, 'Claude/Anthropic identifier present'],
    [/gemini|bard\b/i, 'Gemini/Bard identifier present'],
    [/llama\s?\d|meta ai/i, 'LLaMA identifier present'],
    [/copilot|bing chat/i, 'Copilot identifier present'],
    [/generated (with|by|using) (an )?(ai|language model|assistant)/i, 'Explicit "generated by AI" statement'],
  ]
  for (const [re, label] of TRACE_PATTERNS) {
    if (re.test(lower)) { maxScore = Math.max(maxScore, 88); signals.push({ label, suspicious: true }) }
  }

  if (!signals.length) signals.push({ label: 'No watermark clusters or explicit AI provenance strings found', suspicious: false })
  return { score: maxScore, signals, confidence: maxScore > 0 ? 'high' : 'low' }
}

// ─── Fusion (same spirit as the image fuse(): weighted, explainable) ─────────
function fuseText(stats, structure, traces, model) {
  const sw = 0.45                      // statistical stylometry
  const uw = structure.signals.some(s => s.suspicious) ? 0.2 : 0.08
  const tw = traces.score > 0 ? 0.3 : 0.02
  const mw = model ? 0.35 : 0
  const total = sw + uw + tw + mw
  const parts =
    stats.score * sw +
    structure.score * uw +
    (traces.score || 10) * tw +
    (model ? model.aiScore * mw : 0)
  let score = Math.round(parts / total)
  if (traces.score >= 88) score = Math.max(score, 90) // explicit provenance dominates
  return clamp(score, 1, 99)
}

function uncertaintyBandText(score, statsConf, hasModel, structure, traces) {
  const confRank = { high: 0, medium: 1, low: 2, none: 3 }
  let rank = Math.max(confRank[statsConf] ?? 3, hasModel ? 1 : 2)
  if (traces.score > 0) rank = 0
  if (structure.signals.some(s => s.suspicious)) rank = Math.min(rank, 1)
  let half = [6, 11, 18, 26][rank]
  if (!hasModel) half += 6
  const lo = clamp(score - half, 0, 100)
  const hi = clamp(score + half, 0, 100)
  return { lo, hi, label: `${lo}–${hi}%`, width: hi - lo }
}

function computeVerdictText(score, band) {
  const overlapUncertain = band.lo < 60 && band.hi >= 38
  if (score >= 85 && band.lo >= 78) return { level: 'definitive-ai', emoji: '🤖', color: '#ef4444', line1: 'This text is AI-generated' }
  if (score >= 60) return { level: 'likely-ai', emoji: '⚠️', color: '#f97316', line1: 'This text appears to be AI-generated' }
  if (overlapUncertain) return { level: 'uncertain', emoji: '🤔', color: '#eab308', line1: "We're uncertain about this text" }
  if (score >= 15) return { level: 'likely-real', emoji: '✅', color: '#22c55e', line1: 'This text appears to be human-written' }
  return { level: 'definitive-real', emoji: '✅', color: '#22c55e', line1: 'Strong human-writing signals throughout' }
}

const annotate = arr => (arr || []).map(s => ({ ...s, why: s.why || explainSignal(s.label) }))

/**
 * Full text-analysis pipeline. Returns the same response envelope as the image
 * detector so one shared UI renders both.
 */
export async function analyzeTextPassage(text) {
  const clean = String(text || '').slice(0, 20_000)
  const stats = analyzeTextFeatures(clean)
  if (stats.score == null) {
    return { kind: 'text', score: null, ...stats } // too-short input passthrough
  }
  const structure = analyzeTextStructure(clean)
  const traces = scanAiTraces(clean)

  let model = null, modelError = null
  try { model = await classifyTextWithWorker(clean) } catch (e) { modelError = String(e?.message || e).slice(0, 120) }

  const score = fuseText(stats, structure, traces, model)
  const band = uncertaintyBandText(score, stats.confidence, !!model, structure, traces)
  const verdict = computeVerdictText(score, band)
  const localization = analyzeTextLocalization(clean)

  return {
    kind: 'text',
    score,
    band,
    verdict,
    confidence: model ? (stats.confidence === 'medium' ? 'medium' : 'low') : stats.confidence,
    degraded: !model,
    degradedReason: model ? null : 'Heuristic stylometry only — configure MODEL_WORKER_URL to attach the RoBERTa-style classifier for a neural second opinion.',
    modelError,
    layers: {
      models: {
        available: !!model,
        degraded: !model,
        reason: model ? null : 'no text classifier attached',
        combined: model?.aiScore ?? null,
        results: model ? [{ name: model.name, shortName: 'worker:text', weight: 0.55, aiScore: model.aiScore }] : [],
        failed: modelError ? [modelError] : [],
        disagreement: false, spread: 0,
        confidence: model ? 'medium' : 'very_low',
      },
      statistics: { ...stats, score: stats.score, signals: annotate(stats.signals) },
      structure: { ...structure, signals: annotate(structure.signals) },
      traces: { ...traces, signals: annotate(traces.signals) },
    },
    saliency: localization || undefined,
    featuresShown: stats.features,
    analyzedAt: Date.now(),
    privacy: 'Text is analyzed transiently and never stored.',
  }
}
